name: swift_slides
description: A highly customizable and powerful carousel widget for Flutter.
version: 1.0.0
homepage: https://github.com/Dsachith/advanced_carousel
repository: https://github.com/Dsachith/advanced_carousel
issue_tracker: https://github.com/Dsachith/advanced_carousel/issues

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

# License
license: MIT
